### ISSUE TITLE
Please change the page analytics or remove

### ISSUE THREAD

**Issue by Zhengqbbb** [traderfour/docs#1]
the key is my website analytics key😂
Didn't think anyone would fork it before, please remove or change. Thx ~
https://github.com/traderfour/docs/blob/739cb9a523e9f7f2c2623b024d7554b52fa98bf9/.vitepress/theme/index.ts#L43

**Comment by parsajiravand-trader4** [comment]
@Zhengqbbb
 Hello,My friend thanks for your comment.
  I`ll remove this key on next update.
Best regards

**Comment by Zhengqbbb** [comment]
I hope to have the removal done by Friday if possible Thanks

**Comment by t4-muhammad** [comment]
@Zhengqbbb Hey man, I hope you doing well, Sorry for our late. We release build 0.0.1 and remove all meta data related to your project or personal pages and/or socials. 

Thank you for your time, work and patient. 

Good for you.
